spring.application.name=boot
server.servlet.context-path=/sistema/api/v1
server.port=8080

service.products=list

#Creacion de configuracion personalizada de la aplicacion

#nombre de la aplicacion
app.name=Sistema de productos
#la version
app.version=1.0.0
#autor
app.autor=Desarrollos inovadores S.A.
#idioma
app.language=es
#pais
app.country=Peru